"""initial energy dashboard schema"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("location", sa.String(length=255), nullable=False),
        sa.Column(
            "phase_type",
            sa.Enum("single_phase", "three_phase", name="phase_type"),
            nullable=False,
        ),
        sa.Column("rated_power_kw", sa.Double(), nullable=False),
        sa.Column(
            "criticality",
            sa.Enum("low", "medium", "high", "critical", name="criticality"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rated_power_kw > 0", name="ck_devices_rated_power_positive"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("viewer", "operator", "admin", name="user_role"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "alarms",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.Column("alarm_type", sa.String(length=100), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("triggered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.Uuid(), nullable=True),
        sa.Column("acknowledgement_note", sa.Text(), nullable=True),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("open", "acknowledged", "cleared", name="alarm_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["acknowledged_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_alarms_status_severity_triggered_desc",
        "alarms",
        ["status", "severity", sa.literal_column("triggered_at DESC")],
        unique=False,
    )
    op.create_table(
        "anomalies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("anomaly_type", sa.String(length=100), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("low", "medium", "high", "critical", name="severity"),
            nullable=False,
        ),
        sa.Column("metric", sa.String(length=100), nullable=False),
        sa.Column("actual_value", sa.Double(), nullable=True),
        sa.Column("expected_value", sa.Double(), nullable=True),
        sa.Column("score", sa.Double(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "reviewed", "cleared", name="anomaly_status"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_anomalies_status_detected_desc",
        "anomalies",
        ["status", sa.literal_column("detected_at DESC")],
        unique=False,
    )
    op.create_table(
        "forecasts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_minutes", sa.Integer(), nullable=False),
        sa.Column("predicted_power_kw", sa.Double(), nullable=False),
        sa.Column("lower_kw", sa.Double(), nullable=True),
        sa.Column("upper_kw", sa.Double(), nullable=True),
        sa.Column("model_version", sa.String(length=128), nullable=False),
        sa.CheckConstraint("horizon_minutes > 0", name="ck_forecasts_horizon_positive"),
        sa.CheckConstraint(
            "lower_kw IS NULL OR upper_kw IS NULL OR lower_kw <= upper_kw",
            name="ck_forecasts_bounds",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_forecasts_target_generated_desc",
        "forecasts",
        ["target_at", sa.literal_column("generated_at DESC")],
        unique=False,
    )
    op.create_table(
        "measurements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("voltage_v", sa.Double(), nullable=True),
        sa.Column("current_a", sa.Double(), nullable=True),
        sa.Column("active_power_kw", sa.Double(), nullable=True),
        sa.Column("reactive_power_kvar", sa.Double(), nullable=True),
        sa.Column("apparent_power_kva", sa.Double(), nullable=True),
        sa.Column("power_factor", sa.Double(), nullable=True),
        sa.Column("frequency_hz", sa.Double(), nullable=True),
        sa.Column("energy_kwh_total", sa.Numeric(precision=18, scale=6), nullable=True),
        sa.Column(
            "data_quality",
            sa.Enum("good", "suspect", "missing", name="data_quality"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "active_power_kw IS NULL OR active_power_kw BETWEEN -2000 AND 2000",
            name="ck_measurements_active_power",
        ),
        sa.CheckConstraint(
            "current_a IS NULL OR current_a BETWEEN 0 AND 2000",
            name="ck_measurements_current",
        ),
        sa.CheckConstraint(
            "energy_kwh_total IS NULL OR energy_kwh_total >= 0",
            name="ck_measurements_energy",
        ),
        sa.CheckConstraint(
            "frequency_hz IS NULL OR frequency_hz BETWEEN 40 AND 70",
            name="ck_measurements_frequency",
        ),
        sa.CheckConstraint(
            "power_factor IS NULL OR power_factor BETWEEN 0 AND 1",
            name="ck_measurements_power_factor",
        ),
        sa.CheckConstraint(
            "voltage_v IS NULL OR voltage_v BETWEEN 0 AND 1000",
            name="ck_measurements_voltage",
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "device_id", "measured_at", name="uq_measurements_device_measured_at"
        ),
    )
    op.create_index(
        "ix_measurements_device_measured_at_desc",
        "measurements",
        ["device_id", sa.literal_column("measured_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_measurements_measured_at_desc",
        "measurements",
        [sa.literal_column("measured_at DESC")],
        unique=False,
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "system_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "event_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=True),
        sa.Column("entity_id", sa.String(length=128), nullable=True),
        sa.Column("details_json", sa.JSON(), server_default="{}", nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_system_events_event_at_desc",
        "system_events",
        [sa.literal_column("event_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_system_events_event_at_desc", table_name="system_events")
    op.drop_table("system_events")
    op.drop_table("settings")
    op.drop_index("ix_measurements_measured_at_desc", table_name="measurements")
    op.drop_index("ix_measurements_device_measured_at_desc", table_name="measurements")
    op.drop_table("measurements")
    op.drop_index("ix_forecasts_target_generated_desc", table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_index("ix_anomalies_status_detected_desc", table_name="anomalies")
    op.drop_table("anomalies")
    op.drop_index("ix_alarms_status_severity_triggered_desc", table_name="alarms")
    op.drop_table("alarms")
    op.drop_table("users")
    op.drop_table("devices")
    for enum_name in (
        "alarm_status",
        "anomaly_status",
        "data_quality",
        "severity",
        "user_role",
        "criticality",
        "phase_type",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))
    # ### end Alembic commands ###
