/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/alarms': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Alarms */
    get: operations['alarms_api_v1_alarms_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/alarms/{alarm_id}/acknowledge': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Acknowledge Alarm */
    patch: operations['acknowledge_alarm_api_v1_alarms__alarm_id__acknowledge_patch']
    trace?: never
  }
  '/api/v1/anomalies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Anomalies */
    get: operations['anomalies_api_v1_anomalies_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/login': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Login */
    post: operations['login_api_v1_auth_login_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/logout': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/auth/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Me */
    get: operations['me_api_v1_auth_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/dashboard/summary': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Dashboard Summary */
    get: operations['dashboard_summary_api_v1_dashboard_summary_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/devices': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Devices */
    get: operations['devices_api_v1_devices_get']
    put?: never
    /** Create Device */
    post: operations['create_device_api_v1_devices_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/devices/{device_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Device */
    patch: operations['update_device_api_v1_devices__device_id__patch']
    trace?: never
  }
  '/api/v1/energy/daily': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Daily Energy */
    get: operations['daily_energy_api_v1_energy_daily_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/events': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Events */
    get: operations['events_api_v1_events_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/forecasts/latest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Latest Forecast */
    get: operations['latest_forecast_api_v1_forecasts_latest_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/ingest/measurements': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Ingest Measurement Batch */
    post: operations['ingest_measurement_batch_api_v1_ingest_measurements_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/measurements/history': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Measurement History */
    get: operations['measurement_history_api_v1_measurements_history_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/measurements/latest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Latest Measurements */
    get: operations['latest_measurements_api_v1_measurements_latest_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Settings */
    get: operations['settings_api_v1_settings_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/settings/{key}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    /** Update Setting */
    patch: operations['update_setting_api_v1_settings__key__patch']
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Health
     * @description Return process liveness without touching the database.
     */
    get: operations['health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/ready': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Readiness */
    get: operations['readiness_ready_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AlarmAcknowledgeRequest */
    AlarmAcknowledgeRequest: {
      /** Note */
      note: string
    }
    /** AlarmAcknowledgeResponse */
    AlarmAcknowledgeResponse: {
      alarm: components['schemas']['AlarmItem']
    }
    /** AlarmItem */
    AlarmItem: {
      /** Acknowledged At */
      acknowledged_at: string | null
      /** Acknowledged By */
      acknowledged_by: string | null
      /** Acknowledgement Note */
      acknowledgement_note: string | null
      /** Alarm Type */
      alarm_type: string
      /** Cleared At */
      cleared_at: string | null
      /** Device Id */
      device_id: string | null
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Message */
      message: string
      severity: components['schemas']['Severity']
      /** Source */
      source: string
      status: components['schemas']['LifecycleStatus']
      /**
       * Triggered At
       * Format: date-time
       */
      triggered_at: string
    }
    /** AnomalyItem */
    AnomalyItem: {
      /** Actual Value */
      actual_value: number | null
      /** Anomaly Type */
      anomaly_type: string
      /**
       * Detected At
       * Format: date-time
       */
      detected_at: string
      /**
       * Device Id
       * Format: uuid
       */
      device_id: string
      /** Expected Value */
      expected_value: number | null
      /** Explanation */
      explanation: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Metric */
      metric: string
      /** Score */
      score: number
      severity: components['schemas']['Severity']
      status: components['schemas']['AnomalyStatus']
    }
    /**
     * AnomalyStatus
     * @enum {string}
     */
    AnomalyStatus: 'open' | 'reviewed' | 'cleared'
    /** CountByDeviceStatus */
    CountByDeviceStatus: {
      /**
       * Disabled
       * @default 0
       */
      disabled: number
      /**
       * Offline
       * @default 0
       */
      offline: number
      /**
       * Online
       * @default 0
       */
      online: number
      /**
       * Stale
       * @default 0
       */
      stale: number
    }
    /** CountBySeverity */
    CountBySeverity: {
      /**
       * Critical
       * @default 0
       */
      critical: number
      /**
       * High
       * @default 0
       */
      high: number
      /**
       * Low
       * @default 0
       */
      low: number
      /**
       * Medium
       * @default 0
       */
      medium: number
    }
    /**
     * Criticality
     * @enum {string}
     */
    Criticality: 'low' | 'medium' | 'high' | 'critical'
    /** DailyEnergyItem */
    DailyEnergyItem: {
      /** Completeness Pct */
      completeness_pct: number
      /**
       * Day
       * Format: date
       */
      day: string
      /** Device Id */
      device_id: string | null
      /** Energy Kwh */
      energy_kwh: string | null
      /** Peak Demand Kw */
      peak_demand_kw: number | null
    }
    /** DailyEnergyResponse */
    DailyEnergyResponse: {
      /** Items */
      items: components['schemas']['DailyEnergyItem'][]
      /** Timezone */
      timezone: string
    }
    /** DashboardSummary */
    DashboardSummary: {
      active_alarms: components['schemas']['CountBySeverity']
      /** Current Demand Change Pct */
      current_demand_change_pct: number | null
      /** Current Demand Kw */
      current_demand_kw: number | null
      /** Data Completeness Pct */
      data_completeness_pct: number
      /** Demand Limit Kw */
      demand_limit_kw: number | null
      devices: components['schemas']['CountByDeviceStatus']
      /** Energy Today Kwh */
      energy_today_kwh: string | null
      /** Energy Vs Previous Pct */
      energy_vs_previous_pct: number | null
      /** Excluded Stale Devices */
      excluded_stale_devices: number
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string
      /** Peak Demand At */
      peak_demand_at: string | null
      /** Peak Demand Kw */
      peak_demand_kw: number | null
      /** Timezone */
      timezone: string
    }
    /** DeviceCreateRequest */
    DeviceCreateRequest: {
      /** Code */
      code: string
      criticality: components['schemas']['Criticality']
      /**
       * Enabled
       * @default true
       */
      enabled: boolean
      /** Location */
      location: string
      /** Name */
      name: string
      phase_type: components['schemas']['PhaseType']
      /** Rated Power Kw */
      rated_power_kw: number
    }
    /** DeviceItem */
    DeviceItem: {
      /** Code */
      code: string
      criticality: components['schemas']['Criticality']
      /** Enabled */
      enabled: boolean
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Last Seen At */
      last_seen_at: string | null
      /** Location */
      location: string
      /** Name */
      name: string
      phase_type: components['schemas']['PhaseType']
      /** Rated Power Kw */
      rated_power_kw: number
      status: components['schemas']['DeviceStatus']
    }
    /** DeviceMutationResponse */
    DeviceMutationResponse: {
      device: components['schemas']['DeviceItem']
    }
    /**
     * DeviceStatus
     * @enum {string}
     */
    DeviceStatus: 'online' | 'stale' | 'offline' | 'disabled'
    /** DeviceUpdateRequest */
    DeviceUpdateRequest: {
      /** Code */
      code?: string | null
      criticality?: components['schemas']['Criticality'] | null
      /** Enabled */
      enabled?: boolean | null
      /** Location */
      location?: string | null
      /** Name */
      name?: string | null
      phase_type?: components['schemas']['PhaseType'] | null
      /** Rated Power Kw */
      rated_power_kw?: number | null
    }
    /** EventItem */
    EventItem: {
      /** Actor User Id */
      actor_user_id: string | null
      /** Details Json */
      details_json: {
        [key: string]: unknown
      }
      /** Entity Id */
      entity_id: string | null
      /** Entity Type */
      entity_type: string | null
      /**
       * Event At
       * Format: date-time
       */
      event_at: string
      /** Event Type */
      event_type: string
      /** Id */
      id: number
    }
    /** ForecastItem */
    ForecastItem: {
      /** Device Id */
      device_id: string | null
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string
      /** Horizon Minutes */
      horizon_minutes: number
      /** Lower Kw */
      lower_kw: number | null
      /** Model Version */
      model_version: string
      /** Predicted Power Kw */
      predicted_power_kw: number
      /**
       * Target At
       * Format: date-time
       */
      target_at: string
      /** Upper Kw */
      upper_kw: number | null
    }
    /** ForecastResponse */
    ForecastResponse: {
      /** Items */
      items: components['schemas']['ForecastItem'][]
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /**
     * HealthResponse
     * @description Process-only liveness response.
     */
    HealthResponse: {
      /**
       * Service
       * @constant
       */
      service: 'energy-dashboard-api'
      /**
       * Status
       * @constant
       */
      status: 'ok'
      /** Version */
      version: string
    }
    /** HistoryPoint */
    HistoryPoint: {
      /**
       * Bucket At
       * Format: date-time
       */
      bucket_at: string
      /** Completeness Pct */
      completeness_pct: number
      /** Sample Count */
      sample_count: number
      /** Value */
      value: number | null
    }
    /** HistoryResponse */
    HistoryResponse: {
      /** Series */
      series: components['schemas']['HistorySeries'][]
      /** Timezone */
      timezone: string
    }
    /** HistorySeries */
    HistorySeries: {
      /**
       * Device Id
       * Format: uuid
       */
      device_id: string
      /** Interval */
      interval: string
      /** Metric */
      metric: string
      /** Points */
      points: components['schemas']['HistoryPoint'][]
    }
    /** IngestionError */
    IngestionError: {
      /** Field */
      field: string
      /** Reason */
      reason: string
      /** Record Index */
      record_index: number
    }
    /** LatestMeasurement */
    LatestMeasurement: {
      /** Active Power Kw */
      active_power_kw: number | null
      /** Current A */
      current_a: number | null
      /** Data Quality */
      data_quality: string | null
      /** Device Code */
      device_code: string
      /**
       * Device Id
       * Format: uuid
       */
      device_id: string
      /** Frequency Hz */
      frequency_hz: number | null
      /** Measured At */
      measured_at: string | null
      /** Power Factor */
      power_factor: number | null
      status: components['schemas']['DeviceStatus']
      /** Voltage V */
      voltage_v: number | null
    }
    /**
     * LifecycleStatus
     * @enum {string}
     */
    LifecycleStatus: 'open' | 'acknowledged' | 'cleared'
    /** LoginRequest */
    LoginRequest: {
      /**
       * Email
       * Format: email
       */
      email: string
      /**
       * Password
       * Format: password
       */
      password: string
    }
    /** LoginResponse */
    LoginResponse: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string
      user: components['schemas']['UserIdentity']
    }
    /** LogoutResponse */
    LogoutResponse: {
      /**
       * Status
       * @default logged_out
       */
      status: string
    }
    /** MeasurementIngestBatch */
    MeasurementIngestBatch: {
      /** Records */
      records: {
        [key: string]: unknown
      }[]
      /**
       * Source
       * @enum {string}
       */
      source: 'simulator' | 'gateway'
    }
    /** MeasurementIngestResponse */
    MeasurementIngestResponse: {
      /** Accepted Count */
      accepted_count: number
      /** Duplicate Count */
      duplicate_count: number
      /** Errors */
      errors: components['schemas']['IngestionError'][]
      /** Rejected Count */
      rejected_count: number
    }
    /** Page[AlarmItem] */
    Page_AlarmItem_: {
      /** Items */
      items: components['schemas']['AlarmItem'][]
      /** Page */
      page: number
      /** Page Size */
      page_size: number
      /** Total */
      total: number
    }
    /** Page[AnomalyItem] */
    Page_AnomalyItem_: {
      /** Items */
      items: components['schemas']['AnomalyItem'][]
      /** Page */
      page: number
      /** Page Size */
      page_size: number
      /** Total */
      total: number
    }
    /** Page[DeviceItem] */
    Page_DeviceItem_: {
      /** Items */
      items: components['schemas']['DeviceItem'][]
      /** Page */
      page: number
      /** Page Size */
      page_size: number
      /** Total */
      total: number
    }
    /** Page[EventItem] */
    Page_EventItem_: {
      /** Items */
      items: components['schemas']['EventItem'][]
      /** Page */
      page: number
      /** Page Size */
      page_size: number
      /** Total */
      total: number
    }
    /**
     * PhaseType
     * @enum {string}
     */
    PhaseType: 'single_phase' | 'three_phase'
    /** ReadinessResponse */
    ReadinessResponse: {
      /**
       * Database
       * @constant
       */
      database: 'ready'
      /**
       * Migrations
       * @constant
       */
      migrations: 'at_head'
      /** Revision */
      revision: string
      /**
       * Status
       * @constant
       */
      status: 'ready'
    }
    /** SettingItem */
    SettingItem: {
      /** Description */
      description: string
      /** Key */
      key: string
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string
      /** Value Json */
      value_json: unknown
    }
    /** SettingUpdateRequest */
    SettingUpdateRequest: {
      /** Value */
      value: unknown
    }
    /** SettingUpdateResponse */
    SettingUpdateResponse: {
      setting: components['schemas']['SettingItem']
    }
    /**
     * Severity
     * @enum {string}
     */
    Severity: 'low' | 'medium' | 'high' | 'critical'
    /** UserIdentity */
    UserIdentity: {
      /**
       * Email
       * Format: email
       */
      email: string
      /**
       * Id
       * Format: uuid
       */
      id: string
      role: components['schemas']['UserRole']
    }
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: 'viewer' | 'operator' | 'admin'
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>
      /** Input */
      input?: unknown
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  alarms_api_v1_alarms_get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        status?: components['schemas']['LifecycleStatus'] | null
        severity?: components['schemas']['Severity'] | null
        device_id?: string | null
        from?: string | null
        to?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_AlarmItem_']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  acknowledge_alarm_api_v1_alarms__alarm_id__acknowledge_patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        alarm_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AlarmAcknowledgeRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AlarmAcknowledgeResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  anomalies_api_v1_anomalies_get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        status?: components['schemas']['AnomalyStatus'] | null
        severity?: components['schemas']['Severity'] | null
        device_id?: string | null
        from?: string | null
        to?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_AnomalyItem_']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  login_api_v1_auth_login_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LoginResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LogoutResponse']
        }
      }
    }
  }
  me_api_v1_auth_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UserIdentity']
        }
      }
    }
  }
  dashboard_summary_api_v1_dashboard_summary_get: {
    parameters: {
      query?: {
        timezone?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DashboardSummary']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  devices_api_v1_devices_get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        enabled?: boolean | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_DeviceItem_']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  create_device_api_v1_devices_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DeviceCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeviceMutationResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_device_api_v1_devices__device_id__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        device_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['DeviceUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DeviceMutationResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  daily_energy_api_v1_energy_daily_get: {
    parameters: {
      query: {
        from_date: string
        to_date: string
        timezone?: string
        device_id?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['DailyEnergyResponse']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  events_api_v1_events_get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        event_type?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Page_EventItem_']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  latest_forecast_api_v1_forecasts_latest_get: {
    parameters: {
      query: {
        horizon_minutes: number
        device_id?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ForecastResponse']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  ingest_measurement_batch_api_v1_ingest_measurements_post: {
    parameters: {
      query?: never
      header?: {
        'X-Ingest-Key'?: string | null
      }
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['MeasurementIngestBatch']
      }
    }
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MeasurementIngestResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  measurement_history_api_v1_measurements_history_get: {
    parameters: {
      query: {
        device_id: string[]
        from: string
        to: string
        interval: 'raw' | '10s' | '1m' | '15m' | '1h' | '1d'
        metric:
          | 'voltage_v'
          | 'current_a'
          | 'active_power_kw'
          | 'reactive_power_kvar'
          | 'apparent_power_kva'
          | 'power_factor'
          | 'frequency_hz'
          | 'energy_kwh_total'
        timezone?: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HistoryResponse']
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  latest_measurements_api_v1_measurements_latest_get: {
    parameters: {
      query?: {
        device_id?: string[] | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LatestMeasurement'][]
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  settings_api_v1_settings_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SettingItem'][]
        }
      }
      /** @description Invalid query parameters */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          /**
           * @example {
           *       "error": {
           *         "code": "INVALID_DATE_RANGE",
           *         "details": {
           *           "field": "to"
           *         },
           *         "message": "The end timestamp must be after the start timestamp.",
           *         "request_id": "01J5EXAMPLE"
           *       }
           *     }
           */
          'application/json': unknown
        }
      }
    }
  }
  update_setting_api_v1_settings__key__patch: {
    parameters: {
      query?: never
      header?: never
      path: {
        key: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SettingUpdateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SettingUpdateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HealthResponse']
        }
      }
    }
  }
  readiness_ready_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['ReadinessResponse']
        }
      }
    }
  }
}
